/* Create table for the react converted project */

CREATE TABLE products (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name varchar(40) NOT NULL,
price varchar(80) NOT NULL,
image varchar(100)
);

/* Create the different products for the react converted */

/* Multiple users */
INSERT INTO products
(name, price, image)
VALUES
('MacBook', 1400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 7400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 4400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 5400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 1400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 3400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 9400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 6400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 8400, 'https://i.imgur.com/aSAQnVC.jpg'),
('MacBook', 4400, 'https://i.imgur.com/aSAQnVC.jpg');






/* Creating the table */
CREATE TABLE products (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name varchar(40) NOT NULL,
title varchar(80) NOT NULL,
price integer
);

/* Single user */
INSERT INTO products
(name, title, price)
VALUES
('Wonderful Product1', 'This Product is loving', 260);

/* Multiple users */
INSERT INTO products
(name, title, price)
VALUES
('Wonderful Product1', 'This Product is loving', 260),
('Wonderful Product2', 'This Product is loving', 270),
('Wonderful Product3', 'This Product is loving', 220),
('Wonderful Product4', 'This Product is loving', 260),
('Wonderful Product5', 'This Product is loving', 240),
('Wonderful Product6', 'This Product is loving', 26),
('Wonderful Product7', 'This Product is loving', 29);




/* updating the user */
UPDATE products
SET name = 'new Value'
WHERE id = 2;


/* deleting the user */
DELETE FROM products
WHERE id = 3;

/* deletes the table */
DROP TABLE